FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./hobby-code .

RUN mkdir -p /certs

CMD uvicorn main:app --host 0.0.0.0 --ssl-keyfile /certs/privkey.pem --ssl-certfile /certs/fullchain.pem
